// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHnMhtMH_DLfWUT9WZsnPy4YVcddFNryA',
    appId: '1:923085978036:web:08036bfa8a48b56eafdae1',
    messagingSenderId: '923085978036',
    projectId: 'planeta-d1ea3',
    authDomain: 'planeta-d1ea3.firebaseapp.com',
    storageBucket: 'planeta-d1ea3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUCkQ8mLx2t8C0Tx6xlDxcVnww8YCAQKU',
    appId: '1:923085978036:android:a4186c57b1f083abafdae1',
    messagingSenderId: '923085978036',
    projectId: 'planeta-d1ea3',
    storageBucket: 'planeta-d1ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhELHPEWLhliFjOsV4W2MAbHzbd-b_uE',
    appId: '1:923085978036:ios:cd00e7309d7b8a50afdae1',
    messagingSenderId: '923085978036',
    projectId: 'planeta-d1ea3',
    storageBucket: 'planeta-d1ea3.firebasestorage.app',
    iosBundleId: 'com.example.planetaApp',
  );

}